site_name: Spring MVC Guide
nav:
    - Home: index.md
    - About: about.md
    - 'Introduction':
        - 'What is Spring MVC?': intro/what-is-spring-mvc.md
        - 'Milestones in Spring': intro/milestones-in-spring.md
        - 'Architecture': intro/architecture.md
        - 'Vocabulary': intro/vocabulary.md
    - 'Lesson 1':
        - 'Intro to Project': something.md
        - 'Tools and Setup': something.md
        - 'Configuration Steps': something.md
        - 'Creating Your First Controller': something.md
        - 'Creating Your First JSP': something.md
        - 'Running the Application': something.md
theme: material